# Generated by Django 4.1.2 on 2022-10-26 19:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='news',
            name='main_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
