# Generated by Django 4.1.2 on 2022-10-28 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_news_main_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 28, 7, 30, 22, 995862, tzinfo=datetime.timezone.utc)),
        ),
    ]
