# Generated by Django 4.1.2 on 2022-10-31 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_tags_alter_news_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 11, 30, 31, 227879, tzinfo=datetime.timezone.utc)),
        ),
    ]
