# Generated by Django 4.1.2 on 2022-10-31 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 23, 44, 41, 320455, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(default='hot', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
