# Generated by Django 4.1.2 on 2022-10-31 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_preview_alter_news_public_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 31, 23, 49, 7, 10368, tzinfo=datetime.timezone.utc)),
        ),
    ]
