# Generated by Django 4.1.2 on 2022-11-28 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 1, 8, 4, 618544, tzinfo=datetime.timezone.utc)),
        ),
    ]
