# Generated by Django 4.1.2 on 2022-11-28 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_public_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='public_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 28, 4, 29, 0, 628657, tzinfo=datetime.timezone.utc)),
        ),
    ]
