# Generated by Django 4.1.2 on 2022-10-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_news_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idk',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
