# Generated by Django 4.1.2 on 2022-10-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_idk_delete_news_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Фидбэк', 'verbose_name_plural': 'Фидбэки'},
        ),
    ]
