# Generated by Django 4.1.2 on 2022-10-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='who',
            new_name='productgroup',
        ),
    ]
