# Generated by Django 4.1.2 on 2022-10-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_is_student_user_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
